config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'page#home'
    get 'distributeur', to: 'page#distributeur'
    get 'btob', to: 'page#btob'
    get 'entreprise', to: 'page#entreprise'
    get 'contact', to: 'contacts#new'
    resources "contacts", only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class ContactsForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "carmelosylla@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
    
    def home
        
    end 
    
    def btob
        
    end 
    
    def distributeur
        
    end
    
    def entreprise
        
    end 
    
    def contact
        
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_background.html.erb
<div class="background">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
</div>

app/views/layouts/_footer.html.erb
<footer>
    </br>
        </br>
        <h1>
            <%= link_to "Accueil", root_path %>
            <%= link_to "  B to B", btob_path %>
            <%= link_to "  Distributeur", distributeur_path %>
            <%= link_to "  Entreprise", entreprise_path %>
            <%= link_to "  Contact", contact_path %>
        </h1>
        <p> Localisez <b> SCEA Blin</b> <%= link_to "Cliquez Ici", "https://www.google.com/maps/place/Gaec+Blin/@47.9487163,0.3041583,14z/data=!4m8!1m2!2m1!1zbWFyYcOuY2hlciDDoCBwcm94aW1pdMOpIGRlIFBhcmlnbsOpLWwnw4l2w6pxdWU!3m4!1s0x47e2f2b547f99539:0xa1060125b218373c!8m2!3d47.9401728!4d0.3297848", :target => "_blank" %></p>
</footer>

app/views/layouts/_form.html.erb
<%= form_for (@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit "Send"%>
  </div>
<% end %>
 

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top affix-top">
    <head>
        <div id="navbar">
            <ul>
                <b>
                    <li><a><b><%= link_to "Accueil", root_path %></b></a></li>
                    <li><a><b><%= link_to "Entreprise", entreprise_path %></b></a></li>
                    <li><a><b><%= link_to "Le Distributeur", distributeur_path %></b></a></li>
                    <li><a><b><%= link_to "B to B", btob_path %></b></a></li>
                    <li><a><b><%= link_to "Contact", contact_path %></b></a></li>
                </b>
            </ul>
        </div>
    </head>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sceablin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/background' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/page/btob.html.erb
<h1 class="container" id="logo">
    <%= link_to root_path do %>
   <%= image_tag "logo.png", class: "logo" %>
<% end %>
</h1>
<head class="style">
        <div class="jumbotron"> 
            <table>
                <th class="style">
                    <%= image_tag "dtb.jpg", class: "logo" %>
                </th>
                <th>
                    <h1 style=" color : white; letter-spacing: -4px; font-size: 6.5em; text-align: center; margin-left: 450px; text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px;">
                          <b>B to B</b>
                    </h1> 
                    <h2 style=" font-size: 3.0em; text-align: center; margin-left: 410px; margin-bottom: 60px; margin-right: 30px;  text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px; color: white;">
                             
                    </h2>
                    <p style=" font-size: 1.6em; text-align: justify; margin-left: 420px; margin-right: 30px; color: #646464;">
                            L'entreprise commercialise ses produits depuis 30 ans. La SCEA a su s'adapter à la demande de sa clientèle et proposer de nouveaux produits.


                    </p>         
                </th>
            </table>
        </div>
        <div class="jumbotron" id="produit">
            <table>
                <th class="style4">
                    <%= image_tag "salade.jpg", class: "logo" %><p></br></p>
                    <%= image_tag "poireau.jpg", class: "logo" %><p></br></p>
                    <%= image_tag "chou.jpg", class: "logo" %><p></br></p>
                    <%= image_tag "epinar.jpg", class: "logo" %><p></br></p>
                    <%= image_tag "tomate.jpg", class: "logo" %><p></br></p>
                </th>
                <th>
                    <h1 style=" color : white; letter-spacing: -4px; font-size: 6.5em; text-align: center; margin-left: 100px; text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px; margin-bottom: 50px">
                          <b>Nos Produits</b>
                    </h1> 
                    <h2 style=" font-size: 3.0em; text-align: center; margin-left: 100px; margin-bottom: 60px; margin-right: 30px;  text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px; color: white;">
                             
                    </h2>
                    <p style=" font-size: 1.6em; text-align: justify; margin-left: 80px; margin-right: 30px; color: #646464;">
                            Salade :</br> 

Du 15 Mars au 15 Novembre</br> </br> 

- Laitue Verte/ Rouge x12 ou 6</br> 

- Batavia Verte/ Rouge x12 ou 6</br> 

- Feuille de chêne Verte/ Rouge x12 ou 6</br> 

- Romaine x9 ou autre</br> </br> 
Poireau</br> 

Du 15 Mai au 15 Avril </br> </br> 

- Poireaux Botte 1kg - 2kg</br> 

- Poireaux sacs 3kg</br> 

- Poireaux vrac 10 kg - 5 kg</br> 

- Poireaux coupé barquette 0.500g flopack</br> </br> 



Poireau BIO </br> </br> 

4000 m2 en deuxième année de conversion,</br> 

Première récolte en octobre 2019</br> 

Chou</br> 

Du 15 Juin au 15 Octobre</br></br> 

- Blanc x6 x8 - 10kg</br> 

- Rouge x6 x8 - 10kg</br> 

- Frisé x6 x8 - 10kg</br> 

Celeri</br>  

Celeri Rave</br> 

Du 15 Juillet au 15 Mars</br> </br> 

- Colis x10 x12 x15 avec feuille début de saison</br> 

 

Celeri Branche </br> 

Du 1 Juin au 1 Octobre</br></br>  

- Colis x5kg ou 10kg</br> 

- Scotché 10 pieds ou 5 pieds</br> </br> 
Epinard</br> 

 

15 Avril 15 Décembre</br> </br> 

 

- Colis 3 et 5kg</br> </br> 
Tomate de Terre</br>  

 

De Juin à Septembre </br>  

20 tonnes par an </br> </br> 

 

- Colis 4 kg</br> 



En lutte intégrée, tomates rondes et coeur de boeuf 
Autres produits cultivés  ( pour vente en direct)</br> </br> 

- Carotte non lavées

- Radis
                    </p>         
                </th>
            </table>
        </div>
        
    </head>

app/views/page/contact.html.erb
<h2>Send Us A Message</h1>

<%= render 'layouts/form' %>

app/views/page/distributeur.html.erb
<h1 class="container" id="logo">
    <%= link_to root_path do %>
   <%= image_tag "logo.png", class: "logo" %>
<% end %>
</h1>
<head class="style">
        <div class="jumbotron"> 
            <table>
                <th class="style">
                    <%= image_tag "dtb.jpg", class: "logo" %>
                </th>
                <th>
                    <h1 style=" color : white; letter-spacing: -4px; font-size: 6.5em; text-align: center; margin-left: 400px; text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px;">
                          <b>Le Distributeur</b>
                    </h1> 
                    <h2 style=" font-size: 3.0em; text-align: center; margin-left: 400px; margin-bottom: 60px; margin-right: 30px;  text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px; color: white;">
                             
                    </h2>
                    <p style=" font-size: 1.6em; text-align: justify; margin-left: 400px; margin-right: 30px; color: #646464;">
                            Le ditributeur automatique de légumes vous propose à n'importe quelle heure de la journée des produits frais et locaux: en effet le distributeur est accessible de 8h à 21h 7j/7.</br>Nous proposons des produits de saison et garantissons la provenance de chacun.</br>Ce distributeur est le premier en Sarthe

                    </p>         
                </th>
            </table>
        </div>
                <div class="container5">
            <div class="row">
                <div class="col-sm-12">
                    <div id="myslider" class="carousel slide" data-ride="carousel">
                        
                        
                        <div class="carousel-inner"role="listbox">
                            <div class="item active" id="img1">
                                <%= image_tag ('cont.jpg') %>
                                <div class="carousel-caption">
                                    <h1>SCEA BLIN</h1>
                                </div>
                                
                            </div>
                            <div class="item" id="img1">
                                <%= image_tag ('dist.jpg') %>
                                <div class="carousel-caption">
                                    <h1>SCEA BLIN</h1>
                                </div>
                                
                            </div>
                            
                        </div>
                        
                    </div>
                    
                </div>
            </div>
        </div>
    </head>

app/views/page/entreprise.html.erb
<h1 class="container" id="logo">
    <%= link_to root_path do %>
   <%= image_tag "logo.png", class: "logo" %>
<% end %>
</h1>
    <head class="style">
        <div class="jumbotron"> 
            <table>
                <th class="style2">
                    <%= image_tag "etp.jpg", class: "logo" %><p></br></p>
                    <%= image_tag "bg.jpg", class: "logo" %>
                </th>
                <th>
                    <h1 style="  color : white; letter-spacing: -4px; font-size: 6.5em; text-align: center; margin-left: 150px;float: top; text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 70px;">
                          <b>L'Entreprise</b>
                    </h1>
                    <h2 style=" font-size: 3.0em; text-align: center; margin-left: 400px; margin-bottom: 60px; margin-right: 30px;  text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px; color: white;">
                             
                    </h2>
                    <p style="margin-top: 85px; font-size: 1.0em; text-align: justify; margin-left: 45px; margin-right: 70px; color: #646464;">
                            Capital</br></br>40 Hectares de plein-champ</br>2 Hectares d'Abris</br>11 salariés</br></br></br> Une situation privilégiée puisqu'elle est à 10 Km du Mans et 1Km de la sortie d'autoroute A28</br></br></br>Certification GLOBALGAP</br>Organisation de producteurs VALDIPOM</br></br></br>
Culture:</br></br>

- Salades 860 000 /an </br>

- Poireaux 400 tonnes/an</br>

- Céleris 90 000/an </br>

- Choux 40 000 /an</br>

- Épinards 30 tonnes/an </br></br>


Circuit de distribution:</br></br>

- Centrale d'Achat</br>

- Magasin direct</br>

- Grossiste</br>

- Vente en direct à la Ferme (Distributeur)
                    </p>         
                </th>
            </table>
        </div>
    </head>
  

app/views/page/home.html.erb
<h1 class="container" id="logo">
    <%= link_to root_path do %>
   <%= image_tag "logo.png", class: "logo" %>
<% end %>
</h1>
    <head class="style">
        <div class="jumbotron"> 
            <table>
                <th>
                    <%= image_tag "pb.jpg", class: "logo" %>
                </th>
                <th>
                    <h1 style=" color : white; letter-spacing: -4px; font-size: 6.5em; text-align: center; margin-left: 400px; text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px;">
                          <b>SCEA BLIN ?</b>
                    </h1> 
                    <h2 style=" font-size: 3.0em; text-align: center; margin-left: 400px; margin-bottom: 60px; margin-right: 30px;  text-shadow: 0 0 3px #FF0000, 0 0 5px #0000FF; margin-right: 30px; color: white;">
                            Qui sont-ils ?
                    </h2>
                    <p style=" font-size: 1.6em; text-align: justify; margin-left: 400px; margin-right: 30px; color: #646464;">
                            Nous sommes maraîchers à Parigné l'évêque. Nous proposons des produits issus de l'agriculture raisonnée tout au long de l'année. Nos légumes sont disponibles en libre service sur l'exploitation grâce au distributeur automatique de légumes et à la vente en direct.
                    </p>         
                </th>
            </table>
        </div>
    </head>